untitled folder/config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'doses/create'

  get 'doses/new'

  get 'doses/destroy'

  resources :cocktails, only: [:show, :index, :new, :create] do
  resources :doses, only: [:create, :new]
  end

  resources :doses, only: [:destroy]
  resources :ingredients, only: [:show]

  root "cocktails#index"

end

untitled folder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

untitled folder/app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

untitled folder/app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :cocktail, :ingredient, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  validates :description, presence: true
  validates :ingredient, presence: true

  belongs_to :cocktail
  belongs_to :ingredient
end

untitled folder/app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :doses
  has_many :cocktails, through: :doses
end

untitled folder/app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :photo, PhotoUploader
end

untitled folder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

untitled folder/app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

untitled folder/app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new()
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new()
    @dose.description = dose_params['description']
    @dose.ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save!
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

untitled folder/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :photo, :photo_cache)
    end
end

untitled folder/app/helpers/application_helper.rb
module ApplicationHelper
end

untitled folder/app/helpers/cocktails_helper.rb
module CocktailsHelper
end

untitled folder/app/helpers/doses_helper.rb
module DosesHelper
end

untitled folder/app/helpers/products_helper.rb
module ProductsHelper
end

untitled folder/app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "Mojito" %>
  <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

untitled folder/app/views/cocktails/index.html.erb
<h1 class="text-center">Your cocktail list</h1>

<div class="text-center padded">
  <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card text-center">

          <% if cocktail.picture %>
            <div class="card-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path @product.photo, height: 300, width: 400, crop: :fill %>')">
            </div>
          <% else %>
            <div class="card-header" style="background-image: url('http://www.seriouseats.com/images/2014/11/20141104-cocktail-party-old-fashioneds-holiday-vicky-wasik-3.jpg')">
            </div>
          <% end %>
          <div class="card-body">
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

untitled folder/app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

untitled folder/app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li><%= dose.description %> | <%= dose.ingredient.name %> | <%= link_to 'Delete', dose_path(dose), method: :delete %></li>
          <% end %>
      </ul>
      <%= link_to 'Add To Recipe', new_cocktail_dose_path(@cocktail) %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

untitled folder/app/views/doses/new.html.erb
<div class="container">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description, placeholder: "Amount" %>
    <%= f.input :ingredient_id, collection: @ingredients %>
    <%= f.button :submit, class: "btn btn-primary"  %>
  <% end %>
</div>

untitled folder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

untitled folder/app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

untitled folder/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

untitled folder/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

untitled folder/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

untitled folder/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= cl_image_tag @product.photo, height: 300, width: 400, crop: :fill %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>